### ISSUE TITLE
C++ compilation issues while building app on Android

### ISSUE THREAD

**Issue by SuhairZain** [react-community/react-native-webgl#17]
Hi,
I've got the NDK installed and the classpath set for gradle-download-task, but when I try to build the app, I get an error from the NDK. This is the log: https://pastebin.com/4qFhKqXy.

I tried to follow the answer at https://stackoverflow.com/a/35178570/2848972, but I was unable to figure out what to do. I ran the following command thinking that it'd solve it, but there doesn't seem to be a change.
`$ANDROID_NDK/build/tools/make_standalone_toolchain.py --archarm --api 14 --install-dir /tmp/my-android-toolchain`

 Could someone please help me with this issue?

**Comment by gre** [comment]
I wonder about this:
`Android NDK: android-9 is unsupported. Using minimum supported version android-14.`

what android ndk version do you have?

**Comment by SuhairZain** [comment]
Hi @gre,
I'm on 15.2.4203891.

**Comment by gre** [comment]
on which OS ?

(I think i'm on `r10e`)

**Comment by SuhairZain** [comment]
MacOS Sierra.

**Comment by Kernael** [comment]
I personally had to install version `r10e` to make it work. Maybe @gre see https://github.com/react-community/react-native-webgl/pull/11/commits that I believe attempted to solve this issue. RNWebGL is looking for `4.8` tools but version is `4.9` since `r10e` or later.

**Comment by gre** [comment]
@Kernael thanks for investigation.

so for me, switching from

```
NDK_TOOLCHAIN_VERSION := 4.8
```

to

```
NDK_TOOLCHAIN_VERSION := clang
```

like you did won't compile with r10e:

```
Error:error: no matching function for call to 'bind'
Error:error: no matching function for call to 'bind'
Error:error: no matching function for call to 'bind'
Error:error: no matching function for call to 'bind'
Error:error: no matching function for call to 'bind'
Error:error: no matching function for call to 'bind'
Error:error: no matching function for call to 'bind'
Error:error: no matching function for call to 'bind'
Error:error: no matching function for call to 'bind'

/usr/local/Cellar/android-ndk-r10e/r10e/sources/cxx-stl/gnu-libstdc++/4.8/include/functional
Error:(1638, 21) error: function cannot return function type '__func_type' (aka 'void (int, int, int, int) __attribute__((pcs("aapcs")))')
Information:(1654, 5) in instantiation of template class 'std::_Bind_helper<false, void (&)(int, int, int, int) __attribute__((pcs("aapcs"))), double, double, double, double>' requested here
Information:(1682, 5) candidate template ignored: couldn't infer template argument '_Result'
Information:(1655, 5) candidate template ignored: substitution failure [with _Func = void (&)(int, int, int, int) __attribute__((pcs("aapcs"))), _BoundArgs = <double, double, double, double>]
Error:(1638, 21) error: function cannot return function type '__func_type' (aka 'void (unsigned int) __attribute__((pcs("aapcs")))')
Information:(1654, 5) in instantiation of template class 'std::_Bind_helper<false, void (&)(unsigned int) __attribute__((pcs("aapcs"))), double>' requested here
Information:(1655, 5) candidate template ignored: substitution failure [with _Func = void (&)(unsigned int) __attribute__((pcs("aapcs"))), _BoundArgs = <double>]
Error:(1638, 21) error: function cannot return function type '__func_type' (aka 'void (float, float, float, float) __attribute__((pcs("aapcs")))')
Information:(1654, 5) in instantiation of template class 'std::_Bind_helper<false, void (&)(float, float, float, float) __attribute__((pcs("aapcs"))), double, double, double, double>' requested here
Information:(1655, 5) candidate template ignored: substitution failure [with _Func = void (&)(float, float, float, float) __attribute__((pcs("aapcs"))), _BoundArgs = <double, double, double, double>]
Error:(1638, 21) error: function cannot return function type '__func_type' (aka 'void (unsigned int, unsigned int) __attribute__((pcs("aapcs")))')
Information:(1654, 5) in instantiation of template class 'std::_Bind_helper<false, void (&)(unsigned int, unsigned int) __attribute__((pcs("aapcs"))), double, double>' requested here
Information:(1655, 5) candidate template ignored: substitution failure [with _Func = void (&)(unsigned int, unsigned int) __attribute__((pcs("aapcs"))), _BoundArgs = <double, double>]
Error:(1638, 21) error: function cannot return function type '__func_type' (aka 'void (unsigned int, unsigned int, unsigned int, unsigned int) __attribute__((pcs("aapcs")))')
Information:(1654, 5) in instantiation of template class 'std::_Bind_helper<false, void (&)(unsigned int, unsigned int, unsigned int, unsigned int) __attribute__((pcs("aapcs"))), double, double, double, double>' requested here
Information:(1655, 5) candidate template ignored: substitution failure [with _Func = void (&)(unsigned int, unsigned int, unsigned int, unsigned int) __attribute__((pcs("aapcs"))), _BoundArgs = <double, double, double, double>]
Error:(1638, 21) error: function cannot return function type '__func_type' (aka 'void (float) __attribute__((pcs("aapcs")))')
Information:(1654, 5) in instantiation of template class 'std::_Bind_helper<false, void (&)(float) __attribute__((pcs("aapcs"))), double>' requested here
Information:(1655, 5) candidate template ignored: substitution failure [with _Func = void (&)(float) __attribute__((pcs("aapcs"))), _BoundArgs = <double>]
Error:(1638, 21) error: function cannot return function type '__func_type' (aka 'void (int) __attribute__((pcs("aapcs")))')
Information:(1654, 5) in instantiation of template class 'std::_Bind_helper<false, void (&)(int) __attribute__((pcs("aapcs"))), double>' requested here
Information:(1655, 5) candidate template ignored: substitution failure [with _Func = void (&)(int) __attribute__((pcs("aapcs"))), _BoundArgs = <double>]
Error:(1638, 21) error: function cannot return function type '__func_type' (aka 'void (unsigned char, unsigned char, unsigned char, unsigned char) __attribute__((pcs("aapcs")))')
Information:(1654, 5) in instantiation of template class 'std::_Bind_helper<false, void (&)(unsigned char, unsigned char, unsigned char, unsigned char) __attribute__((pcs("aapcs"))), double, double, double, double>' requested here
Information:(1655, 5) candidate template ignored: substitution failure [with _Func = void (&)(unsigned char, unsigned char, unsigned char, unsigned char) __attribute__((pcs("aapcs"))), _BoundArgs = <double, double, double, double>]
Error:(1638, 21) error: function cannot return function type '__func_type' (aka 'void (unsigned char) __attribute__((pcs("aapcs")))')
Information:(1654, 5) in instantiation of template class 'std::_Bind_helper<false, void (&)(unsigned char) __attribute__((pcs("aapcs"))), double>' requested here
Information:(1655, 5) candidate template ignored: substitution failure [with _Func = void (&)(unsigned char) __attribute__((pcs("aapcs"))), _BoundArgs = <double>]
Error:(1638, 21) error: function cannot return function type '__func_type' (aka 'void (float, float) __attribute__((pcs("aapcs")))')
Information:(1654, 5) in instantiation of template class 'std::_Bind_helper<false, void (&)(float, float) __attribute__((pcs("aapcs"))), double, double>' requested here
Error:Execution failed for task ':RNWebGL:buildRNWebGLLib'.
> Process 'command '/usr/local/opt/android-ndk-r10e/ndk-build'' finished with non-zero exit value 2
```

**Comment by Kernael** [comment]
@gre Haven't tried this fix myself, but I'm guessing it works only for newer NDK versions

**Comment by gre** [comment]
@SuhairZain could you check if this patch would help you ? https://github.com/react-community/react-native-webgl/pull/11/commits/9c0f12ca45fd6388f57b709445d38a81d84d2f83

**Comment by SuhairZain** [comment]
@gre  I'm trying with the r10e version of NDK right now. Let me if that fixes the issue. Otherwise, I'll try your patch.

**Comment by SuhairZain** [comment]
@Kernael Using `r10e` seems to be working for me. Thanks for the info.
@gre Although I've fixed the problem for now, I'd love to make sure that this lib builds on later versions of NDK as well. Will try your patch in a while.

**Comment by gre** [comment]
yeah i'm not sure how we can unify so that it compiles with both NDK at some point

**Comment by themakerman** [comment]
@SuhairZain can you tell me where should i set the classpath for gradle download task??

**Comment by SuhairZain** [comment]
@themakerman 
It should be inside the android/build.gradle, not the android/app/build.gradle file.
```gradle
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath 'de.undercouch:gradle-download-task:3.1.2' // Put it here

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```

**Comment by themakerman** [comment]
@zoontek exactly. I figured it out. @gre Note the change in docs. Wrongly mentioned the path to be in android/app/build.grade whereas it should be android/build.gradle.

**Comment by themakerman** [comment]
@gre 
![untitled](https://user-images.githubusercontent.com/14818804/31058826-0b89db9a-a72d-11e7-88f9-5ff6ccd99a1c.png)

**Comment by gre** [comment]
ok thanks, fixed the doc

**Comment by Fr33maan** [comment]
@gre The fix worked perfectly for me !

**Comment by gre** [comment]
for now we will have to stick to the same version of Android NDK. if you find a way to make multiple NDK version compiling the same project (like branching some part of the config?) feel free to send a PR

**Comment by Fr33maan** [comment]
@gre As far as I know, to keep 2 branches of the same library the simple solution is to keep 2 active packages on npm with a tag and to have an up to date readme. 
I could PR for make a `ndk-4.9`.

But why do I need the upper version of the ndk ?

**Comment by gre** [comment]
I'm not sure publishing N version on NPM is going to be scalable (but this could still be automated), not sure but I would rather prefer to have a script to run at install or something like this.

It is possible to have many NDK on the same computer right? so maybe the simplest way (maybe not the best of course) is just say in the README that this lib requires to have a specific NDK version.

**Comment by gre** [comment]
I think a ndk-4.9 branch is valuable still, because investigating what changes over NDKs will be interesting. and then we can think what we can do to automate / branch between them

**Comment by st0ffern** [comment]
I get this error too. `:react-native-webgl:buildRNWebGLLib FAILED`
Latest release uses NDK 4.8, changing it to 4.9 solves the problem? why is it reverted to 4.8 ?

Are there other workarounds to make it build that i dont know of?

**Comment by Fr33maan** [comment]
@stoffern The library uses `4.8` for reasons @gre knows. The lib has not been updated to `4.9` but you can do it for your own copy of the library by changing it in `node_modules` folder.
Check the [patch](https://github.com/react-community/react-native-webgl/commit/9c0f12ca45fd6388f57b709445d38a81d84d2f83)

**Comment by gre** [comment]
maybe we should upgrade it all to 4.9 actually, I accept PR for this :)

**Comment by Fr33maan** [comment]
@gre And what about the second part of the patch ? 
`#include <stdlib.h>`

**Comment by st0ffern** [comment]
@gre could be an idea to add the `minSdkVersion 17` to Android build config in the docs 😉

**Comment by gre** [comment]
this is fixed. lib users will need to have an updated android-ndk
