### ISSUE TITLE
Error about es2015, stage-1 and react babel presets not installed

### ISSUE THREAD

**Issue by SuhairZain** [react-community/react-native-webgl#18]
The react native gives an error that it couldn't find the es2015, stage-1 and react presets, like the one below:
```
error: bundling failed: "TransformError: /Users/suhairzain/Documents/test-app/node_modules/react-native-webgl/lib/index.js: Couldn't find preset \"es2015\" relative to directory \"/Users/suhairzain/Documents/test-app/node_modules/react-native-webgl\""
```

Right now, I've managed to get it working by installing these as a dev dependency for my project, but what would be the right way to fix this issue?

**Comment by emilebres** [comment]
That's because `.babelrc` is exported in the npm repository. Just adding it to `.gitignore` should fix this. I opened a pull request #19.
