### ISSUE TITLE
how to improve performance in iOS Simulator?

### ISSUE THREAD

**Issue by gre** [react-community/react-native-webgl#3]
the current performance you get on iOS simulator is quite bad, making really difficult to develop anything WebGL with the simulator.
i'm not sure what we can improve, if it's related to JSC or OpenGL. But I'm pretty sure OpenGL can be performant even in simulator, see for instance examples of gl-react-native v2 (that was doing custom opengl impl in ObjC but not actually implementing webgl api)

**Comment by gre** [comment]
note that on Android Simulator perf are perfectly fine, i'm not sure what's going on in XCode / iOS Simulator

**Comment by johannth** [comment]
This is probably related to this iOS 11 simulator issue: https://forums.developer.apple.com/message/270038?tstart=0

Might be fixed in Xcode 9.1 beta 2 but I haven't checked it out myself.

**Comment by gre** [comment]
thanks for the link, definitely something to track , but I'm pretty sure it was existing before iOS 11.

**Comment by DylanVann** [comment]
This has been an issue since before RN existed. Developing Cocos2D games for iOS it was sometimes impossible to test using the simulator because the difference in performance was so great.

https://stackoverflow.com/a/34126391/2669591
