### ISSUE TITLE
Texture Loading Issues (iOS) (Three JS)

### ISSUE THREAD

**Issue by epochrion** [react-community/react-native-webgl#31]
I get the following error when setting `yflip` to false on iOS:

`Assertion failure in -[GPUImageFramebuffer unlock], /.../node_modules/react-native-
webgl/ios/framework/Source/GPUImageFramebuffer.m:269`

Examining line 269, the following assert is getting invoked:

`NSAssert(framebufferReferenceCount > 0, @"Tried to overrelease a framebuffer, did you forget to call -useNextFrameForImageCapture before using -imageFromCurrentFramebuffer?");`

Thus, textures do not display correctly. The issue does not occur if `yflip` is set to true on iOS. The exact same code runs fine on Android, irrespective of what value `yflip` is set to. At first, this error appeared to be the same as #16 but the scenario for when it does or does not work is reversed for me:

Value of `yflip` | Issue on iOS
--- | ---
true | No
false | Yes

The load texture call that I make is as follows:

```
function loadTexture(data, src, flip) {
  let texture = new THREE.Texture();
  let properties = renderer.properties.get(texture);
  let material = new THREE.MeshBasicMaterial({map: texture, overdraw: 0.5});
  glex.loadTexture({ yflip: flip, image: src })
    .then(({ texture }) => {
      properties.__webglTexture = texture;
      properties.__webglInit = true;
      texture.needsUpdate = true;
    });
  return material;
}
```

Where `glex = gl.getExtension('RN')`, and `flip` is a boolean argument.

Am I perhaps missing something related to when `yflip `can be set to false? Or is there an issue currently with the implementation of `yflip `in react-native-webgl for iOS?

**Comment by epochrion** [comment]
I did a quick test using the [basic texture](https://github.com/react-community/react-native-webgl/blob/master/example/src/BasicTexture.js) example and when `yflip` is set to false, despite getting the same assertion failure, the image of the building still displays correctly. The key difference between the basic texture example and the load texture call provided above appears to be that the first directly invokes the Web GL methods while the latter uses the functionality provided by Three JS. For quick reference, the load texture call used by the basic texture example is as follows:

```
rngl.loadTexture({ image: "https://i.imgur.com/wxqlQkh.jpg", yflip: false })
  .then(({ texture }) => {
    gl.activeTexture(gl.TEXTURE0);
    gl.bindTexture(gl.TEXTURE_2D, texture);
    gl.uniform1i(tLocation, 0);
    gl.drawArrays(gl.TRIANGLES, 0, 3);
    gl.flush();
    rngl.endFrame();
  });
```

Please note that I call `gl.flush()` and `glex.endFrame()` as well in my code. The only difference is that the call is made every frame instead of at the end of every load texture call (see below). Is this okay to do?

```
function animate() {
  requestId = requestAnimationFrame(animate);
  renderer.render(scene, camera);
  // various other function calls here...
  gl.flush();
  glex.endFrame();
}
```

Given that `yflip` set to false works ok with the basic texture example, this leads me to think that the issue may or may not be related to the assertion failure, but could more likely be an issue between react-native-webgl and three.js? Perhaps it is related to how the texture is assigned to the properties object?

**Comment by epochrion** [comment]
There are two key issues that I have identified when loading textures on iOS (in conjunction with Three JS). Descriptions of the issues, along with the expected and actual output, are included below.

**Issue 1:** When loading a set of textures, the very last texture to be loaded fails to render. More specifically, the previous texture will only be rendered when the next texture has been successfully loaded. This occurs when `yflip` is set to true, but I don't think the property itself can be causing this issue.

**Issue 2:** All previously loaded textures will have their original image content replaced by the image content of the newest loaded texture. Thus, all textures render the same image. Though this issue occurs when `yfip` is set to false, there is an underlying texture management issue that needs to be resolved.

I have created an [example project](https://github.com/epochrion/webgl-example/tree/bug/ios/rendering) that can be used to reproduce the two issues. It effectively creates a 3 x 3 grid of textures, with the texture images corresponding to the numbers 1 through 9. A delay of 120 frames is induced between each load texture call to help examine the issues better. A message is logged whenever the load texture callback is invoked, to help identify what should have been rendered on screen.

The expected final results are [this]( https://github.com/epochrion/webgl-example/blob/bug/ios/rendering/screenshots/android/yflip_true.PNG) (when `yflip` is set to true) and [this]( https://github.com/epochrion/webgl-example/blob/bug/ios/rendering/screenshots/android/yflip_false.PNG) (when `yflip` is set to false). Note that these images are taken from an instance of the example project running on Android, where the two issues are not present. Unfortunately, the following results are produced when run on iOS:

`<< yflip = true >>`

| **Console Message** | **Expected Output** | **Actual Output** | **Output Screenshot** |
| :---: | :---: | :---: | :---: |
| Texture [1] Loaded | 1 | *Nothing Rendered* | [1.png](https://github.com/epochrion/webgl-example/blob/bug/ios/rendering/screenshots/ios/yflip_true/yflip_true_1.png) |
| Texture [2] Loaded | 1, 2 | 1 | [2.png](https://github.com/epochrion/webgl-example/blob/bug/ios/rendering/screenshots/ios/yflip_true/yflip_true_2.png) |
| Texture [3] Loaded | 1, 2, 3 | 1, 2 | [3.png](https://github.com/epochrion/webgl-example/blob/bug/ios/rendering/screenshots/ios/yflip_true/yflip_true_3.png) |
| Texture [4] Loaded | 1 ... 4 | 1, 2, 3 | [4.png](https://github.com/epochrion/webgl-example/blob/bug/ios/rendering/screenshots/ios/yflip_true/yflip_true_4.png) |
| Texture [5] Loaded | 1 ... 5 | 1 ... 4 | [5.png](https://github.com/epochrion/webgl-example/blob/bug/ios/rendering/screenshots/ios/yflip_true/yflip_true_5.png) |
| Texture [6] Loaded | 1 ... 6 | 1 ... 5 | [6.png](https://github.com/epochrion/webgl-example/blob/bug/ios/rendering/screenshots/ios/yflip_true/yflip_true_6.png) |
| Texture [7] Loaded | 1 ... 7 | 1 ... 6 | [7.png](https://github.com/epochrion/webgl-example/blob/bug/ios/rendering/screenshots/ios/yflip_true/yflip_true_7.png) |
| Texture [8] Loaded | 1 ... 8 | 1 ... 7 | [8.png](https://github.com/epochrion/webgl-example/blob/bug/ios/rendering/screenshots/ios/yflip_true/yflip_true_8.png) |
| Texture [9] Loaded | 1 ... 9 | 1 ... 8 | [9.png](https://github.com/epochrion/webgl-example/blob/bug/ios/rendering/screenshots/ios/yflip_true/yflip_true_9.png) |

Note that the ellipses (`...`) indicate that all the numbers in between were also rendered. 

The console message is printed at the same time as when the `texture.needsUpdate` flag is set to true. There will be some latency between when the flag is set and when the texture to be rendered is actually updated. This is partially why the example project has a delay of a certain number of frames, as per the interval value set, in order to account for any unexpectedly significant latency. However, the results above show that the previous texture is not rendered until the next texture has been loaded. Texture 9 is never rendered.

`<< yflip = false >>`

| **Console Message** | **Expected Output** | **Actual Output** | **Output Screenshot** |
| :---: | :---: | :---: | :---: |
| Texture [1] Loaded | 1 | 1 | [1.png](https://github.com/epochrion/webgl-example/blob/bug/ios/rendering/screenshots/ios/yflip_false/yflip_false_1.png) |
| Texture [2] Loaded | 1, 2 | 2, 2 | [2.png](https://github.com/epochrion/webgl-example/blob/bug/ios/rendering/screenshots/ios/yflip_false/yflip_false_2.png) |
| Texture [3] Loaded | 1, 2, 3 | 3, 3, 3 | [3.png](https://github.com/epochrion/webgl-example/blob/bug/ios/rendering/screenshots/ios/yflip_false/yflip_false_3.png) |
| Texture [4] Loaded | 1 ... 4 | 4 x4 | [4.png](https://github.com/epochrion/webgl-example/blob/bug/ios/rendering/screenshots/ios/yflip_false/yflip_false_4.png) |
| Texture [5] Loaded | 1 ... 5 | 5 x5 | [5.png](https://github.com/epochrion/webgl-example/blob/bug/ios/rendering/screenshots/ios/yflip_false/yflip_false_5.png) |
| Texture [6] Loaded | 1 ... 6 | 6 x6 | [6.png](https://github.com/epochrion/webgl-example/blob/bug/ios/rendering/screenshots/ios/yflip_false/yflip_false_6.png) |
| Texture [7] Loaded | 1 ... 7 | 7 x7 | [7.png](https://github.com/epochrion/webgl-example/blob/bug/ios/rendering/screenshots/ios/yflip_false/yflip_false_7.png) |
| Texture [8] Loaded | 1 ... 8 | 8 x8 | [8.png](https://github.com/epochrion/webgl-example/blob/bug/ios/rendering/screenshots/ios/yflip_false/yflip_false_8.png) |
| Texture [9] Loaded | 1 ... 9 | 9 x9 | [9.png](https://github.com/epochrion/webgl-example/blob/bug/ios/rendering/screenshots/ios/yflip_false/yflip_false_9.png) |

Note that the multiplication value (`x`) indicates the number of times the same texture is repeated.

Compare the last screenshot in the above table (for Texture 9) to the image of the  correct result linked earlier (on Android), and the issue becomes self-explanatory. Each texture should be unique, not repeated.

Testing was conducted on the following physical devices:
- iPhone 8 (iOS Version 11.2)
- iPhone 5 (iOS Version 10.3.3)
- Pixel XL (Android Version: 8.0.0)

As the example project works correctly on Android, I presume the two issues are specific to the iOS implementation of react-native-webgl. Though the example project could be made to work by setting `yflip` to true and by loading an extra redundant texture at the end of the process, I think that resolving these two issues is integral to ensuring that texture loading and texture rendering on iOS work correctly.

**Comment by wizapp** [comment]
Hi,

   With 1 texture load, with `yflip = true`:

- On iOS simulator, the problem does not occur.
- On physical iPhone X device, texture is not rendered.

   Is it planned to be fixed soon ?

Thx

**Comment by meros** [comment]
I have this problem as well. Flip on iOS device gives blank result. And using flip: false causes mixup of textures.

**Comment by brenwell** [comment]
Me too, any ideas how to get around this

**Comment by brenwell** [comment]
Ok well I have fixed the flipping problem for me but its just a quick hack I have no idea what will be the side effects so use with caution

**Comment by AlexDM0** [comment]
I've also encountered this. My solution was to yflip the UV map in the vertex shader and to yflip: false in the loadTexture. Hope it helps someone!

**Comment by akupila** [comment]
I also encountered this and did the same fix as @AlexDM0.

However,  the issue with texture mixup remains. Not sure if it's related to the same issue, but whenever textures are loaded, only the latest one is applied. If i open the GL debugger in XCode, i can see only one texture is created. I found a workaround for this, which is to _never_ load the exact same texture size. If the dimensions are not 100% the same, both textures are created as expected. I did some digging and found that commenting out the framebuffer cache here fixes the issue: https://github.com/react-community/react-native-webgl/blob/master/ios/framework/Source/GPUImageFramebufferCache.m#L79-L109, although that seems like the wrong thing to do. For now, i'm just loading textures by literally having 1 extra pixel per index, then doing the mapping in reverse for UV coordinates. This is very much an ugly hack but works reliably.

**Comment by gre** [comment]
ideally we need to re-sync the codebase with latest work from Expo, they have improved things so it's definitely interesting to check it out, I think Expo GLView no longer use GPUImage which can help on this issue. one tricky part will be how to keep this "TextureLoader" feature that I think is interesting to keep (allows things like third party libs like react-native-webgl-view-shot to live outside react-native-webgl, basically a lib can add more texture formats to bring support of things loosely (imagine video, camera, view stream or imagine even any usecases like a live stream etc.. we can't put all in one library)).

so to summary this can't go without some architecture refactoring. not sure when i'll have time to start this

**Comment by victorporof** [comment]
Ignoring the `TextureLoader` stuff, how would syncing with Expo work? How much has this fork diverged from upstream?

**Comment by gre** [comment]
Hi @victorporof , the current forked implementation is about one year old from the Expo one. this implementation use GL ES2. Expo's have recently refactored to use GL ES3. I also think they have worked on a WebGL2 support (not exactly sure if it's shipped or in progress)
there were bunch of fixes done as well, I think it is possible to migrate to this implementation but maybe it is wise to wait a few weeks to what Expo is working on because I think they are preparing something around these subjects :)
