### ISSUE TITLE
[Urgent Help] Can gl-waveform be used with react native??

### ISSUE THREAD

**Issue by themakerman** [react-community/react-native-webgl#34]
https://cnpmjs.org/package/gl-waveform

**Comment by gre** [comment]
looks like it depends on `document` a bit https://github.com/audio-lab/gl-waveform/blob/a70d605a799a7d529ebefd4bfa979161135a2b67/src/core.js#L36-L37 so you might have to patch it,

apart from this, it should work. you will have to test if performance are good enough
