### ISSUE TITLE
Error Compiling: Android NDK: android-9 is unsupported. Using minimum supported version android-14.

### ISSUE THREAD

**Issue by rubencg195** [react-community/react-native-webgl#37]
**I get the following error:**

![image](https://user-images.githubusercontent.com/25628940/34085827-8a6fca68-e38d-11e7-9ea5-f5241ede56b5.png)

**The instrucctions says:**

**android/local.properties:** Make sure you have an up-to-date Android NDK (needed to compile the Native C++ code) and that it's properly configured in ANDROID_NDK env or in local.properties file (e.g. ndk.dir=/usr/local/share/android-ndk).
**android/build.gradle:** if it's not already there, add gradle-download-task buildscript dependency: classpath 'de.undercouch:gradle-download-task:3.1.2' . If you don't do this, you will likely have :downloadJSCHeaders not working.
**android/app/build.gradle:** Make sure you have minSdkVersion 17 or higher

The above files are listed below:

**android/local.properties:**

![image](https://user-images.githubusercontent.com/25628940/34085856-fb31100e-e38d-11e7-8352-a9afb3344b0b.png)

**android/build.gradle: **

![image](https://user-images.githubusercontent.com/25628940/34085875-46427c18-e38e-11e7-8981-7d3b87175e41.png)

**android/app/build.gradle:** 

![image](https://user-images.githubusercontent.com/25628940/34085867-1d3c6306-e38e-11e7-922e-cd4c66861536.png)

**My NDK file path is correct:**

![image](https://user-images.githubusercontent.com/25628940/34085880-60de25f4-e38e-11e7-8b0a-f5071a1e20f1.png)

**And my NDK version is not 9 as the error says but 16**

![image](https://user-images.githubusercontent.com/25628940/34085884-706948dc-e38e-11e7-80cd-48293a884cc1.png)

**Comment by kelset** [comment]
The NDK one is actually just a warning.

The error blocking you is a separate issue, which is actually fixed in master by https://github.com/react-community/react-native-webgl/pull/32

Point your package.json to master and reinstall the node_modules.

**Comment by rubencg195** [comment]
Thank you very much, you are correct, that was the error.

![image](https://user-images.githubusercontent.com/25628940/34102908-add1d3c0-e3e2-11e7-8ee7-2dc147768207.png)

I had to change that line at

\node_modules\react-native-webgl\android\src\main\java\fr\greweb\rnwebgl

**Comment by hu-qi** [comment]
Hello, how did you solve it?
