### ISSUE TITLE
Alpha Background on android

### ISSUE THREAD

**Issue by fdecampredon** [react-community/react-native-webgl#41]
Is there a way to have transparent surface background on android ?

**Comment by skizzo** [comment]
+1

`renderer.setClearColor (0x000000, 0);` works just fine on iOS, anybody got an idea why it won't work on Android?

**Comment by anthony-skr** [comment]
+1

**Comment by AlexDM0** [comment]
I'm also trying to get this done. Is there any way to do this? If I simply render an empty webglView with 
```js
      gl.enable( gl.BLEND );
      gl.blendEquationSeparate( gl.FUNC_ADD, gl.FUNC_ADD );
      gl.blendFuncSeparate( gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA, gl.ONE, gl.ONE_MINUS_SRC_ALPHA );

      gl.colorMask(true, true, true, true);
      gl.clearColor(0.0,0.0, 0.0, 0.0);
      gl.clear(gl.COLOR_BUFFER_BIT);
      // ignore texture drawing for this test
      // gl.drawArrays(gl.TRIANGLES, 0, 3);
      gl.flush();
      rngl.endFrame();
```

all I get is a black background.. Any suggestions?

**Comment by skizzo** [comment]
Yeah, I‘m about to look for somebody on Upwork or something, this is a dealbreaker for an app I was working on..

**Comment by gre** [comment]
is this problem fixed in current expo GLView implementation? If yes, maybe worth trying to port latest stuff. actually maybe you guys want to take a look at https://github.com/react-community/react-native-webgl/pull/63 . i have very few time to work on this & maintain this right now, but hopefully I'll have more during this summer

**Comment by armenbadalyan** [comment]
Check my fork https://github.com/armenbadalyan/react-native-webgl/commit/830b2132f7ff9a85ba3fa69c6e975754902eae8a
It makes GLSurfaceView transparent at the cost of placing it above everything else on that view.
