### ISSUE TITLE
iOS throw Exception

### ISSUE THREAD

**Issue by songxiaoliang** [react-community/react-native-webgl#42]
gl-react: 3.13.0
gl-react-native: 3.13.0
react-native-webgl: 0.8.0
react-native: 0.44.3

Running on iOS, the following error appears, looking forward to the author reply as soon as possible

![1517282845846](https://user-images.githubusercontent.com/6975588/35546758-92ea10b4-05b0-11e8-8589-e9ad2b08a57d.jpg)

**Comment by songxiaoliang** [comment]
@gre yeah, I am not sure how to solve this problem, what do you think?

**Comment by gre** [comment]
have you tried with more recent version of React Native? I'll try to run the example project asap

**Comment by songxiaoliang** [comment]
@gre Yes, there is no problem with version 0.50. However, in the 0.44.3 version of the above problems have emerged. But from the abnormal view should not be difficult to solve, please try as soon as possible in the 0.44.3 version and run to view the abnormal results, thank you very much, looking forward to your reply

**Comment by gre** [comment]
sorry but my time is limited and best would be for you to upgrade to latest React Native OR to fork RN/RNwebgl to investigate and fix the problem. If you find a fix that is backward compatible, we can accept a PR.

The react-native-webgl is ambitious and there are so many things to work on, I have very low time nowaday. hope you understand
