### ISSUE TITLE
File 'libRNWebGL.a' doesn't exist

### ISSUE THREAD

**Issue by TheDutchCoder** [react-community/react-native-webgl#43]
I followed the installation instructions, but I can't add `libRNWebGL.a` to my project because it doesn't exist anywhere in the `node_modules` folder.

**Comment by TheDutchCoder** [comment]
Okay I was able to resolve this by manually doing this:

You have to drag the `node_modules/react-native-webgl/ios/RNWebGL.xcodeproj` file into your Xcode  `Libraries`, then you can add the `libRNWebGL.a` to the `Linked Frameworks and Libraries`.

After that it builds (and works) fine.

Might want to update this in the docs.

**Comment by ajRiverav** [comment]
After following the documentation, I am having the same problem. 

@TheDutchCoder: can I just navigate to the *.a file and add it? I was looking for the *.a file and could not find in in the ios folder.

**Comment by TheDutchCoder** [comment]
@ajRiverav I believe you have to drag in the project first, then you'll be able to find the file.

**Comment by apengstrom** [comment]
Had the same issue, I believe this stems from the bug with react-native when linking assets to xcode.

I wonder if this library would solve this issue. Haven't tried it as I've already linked, anyone else want to give it a try?

https://github.com/unimonkiez/react-native-asset

**Comment by Uniphix** [comment]
I am actually getting the stupid 'React/RCTViewManager.h' with the latest react-native version (0.59.1)  when trying to build with iOS.
