### ISSUE TITLE
iOS simulator/ debug JS remotely: onContextCreate() never called / WebGLView not showing

### ISSUE THREAD

**Issue by skizzo** [react-community/react-native-webgl#45]
Hi,
as soon as I start debugging JS remotely on my iOS simulator (iPhone 5s - 9.2), the whole WebGLView just disappears. Any ideas why this might happen?
Thanks!

**Comment by gre** [comment]
yes. react-native-webgl don't support executing JS remotely, it needs to run in JSC by design of the current implementation.
see https://forums.expo.io/t/debugging-glview-on-ios/630
