### ISSUE TITLE
Invariant Violation: Native component for 'RNWebGLView' does not exist

### ISSUE THREAD

**Issue by AndyEsser** [react-community/react-native-webgl#48]
Hello,

I'm trying to implement some WebGL code within a React Native application and I'm stumbling at the first hurdle.

I've tried to follow the instructions in the README about how to set up the React Native application to support the react-native-webgl Component but I am very new t React Native so suspect I'm doing something very silly and simple to fix but I'm just not sure where to look. Any help would be appreciated.

When testing the React Native application either on my Android phone or an Android Emulator I am receiving the following error and stack trace:

`Invariant Violation: Native component for "RNWebGLView" does not exist

This error is located at:
    in RNWebGLView (created by WebGLView)
    in RCTView (at View.js:78)
    in View (created by WebGLView)
    in WebGLView (at Game.js:14)
    in Game (at App.js:8)
    in App (at registerRootComponent.js:35)
    in RootErrorBoundary (at registerRootComponent.js:34)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:78)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:78)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)`

Are there any additional steps after the README steps that I need to do to make this component available to the build process?

**Comment by lukas1596** [comment]
This may be basic, but I was getting the exact same error and was able to solve with the following steps (some of it is the config on the README file, nonetheless it's included in case it helps someone)

- I downloaded the android NDK from the link in [this page](https://facebook.github.io/react-native/docs/building-from-source.html) and extracted it into some directory
- Created the local.properties file and added the `ndk.dir = C:\\AndroidNdk\\android-ndk-r10e` line.
- Commented the `android.useDeprecatedNdk=true` line on the 'android/gradle.properties' file. (saw it somewhere)
- Uninstalled the app from the device and installed it again

This solved the error for me, hope it helps anyone that has the same issue.

**Comment by lukas1596** [comment]
Also, make sure your MainApplication.java has the following line inside the getPackages() method:

protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
            // eg. new VectorIconsPackage()
            new RNWebGLPackage()
        );
}
