### ISSUE TITLE
Frame Flickering

### ISSUE THREAD

**Issue by AndyEsser** [react-community/react-native-webgl#50]
Posted with code and video here: https://stackoverflow.com/questions/49712088/react-native-webgl-flickering

Having an issue with flickering between frames

**Comment by AndyEsser** [comment]
In case anyone else stumbles across this, basically don't do any kind of reading state inside the frame. Do it all beforehand when initialising GL.

This is fairly common knowledge within graphics programming, but I hadn't realised quite how slow it would be in JS/RN (presumably amplified by the latency of the React Bridge)

**Comment by implicit-invocation** [comment]
I ran into the same problem, but without reading state.  
My loop is something like this.  
```
  const loop = () => {
    render();
    rngl.endFrame();

    requestAnimationFrame(loop);
  };

  loop();
```
If I add `gl.getError()` or getting textures' width, height before I call `rngl.endFrame()`, it doesn't flicker as much.  
I suspect that the flickering is caused by `rngl.endFrame()` is not called sequentially with render.

**Comment by AndyEsser** [comment]
What's in your render loop?

**Comment by implicit-invocation** [comment]
```
const render = () => {
  gl.clear(gl.COLOR_BUFFER_BIT);

  batch.begin();
  rotation += Math.PI / 20;
  batch.drawRegion(region, 100, 100, 100, 100, rotation, 50, 50);

  batch.end();
};
```
My batch is using `stackgl/gl-sprite-batch` with `gl-basic-shader`.  
If I comment out the line `gl.clear(gl.COLOR_BUFFER_BIT)`, it looks very smooth, but of course I want to clear the screen.  
I noticed in your video, JS FPS dropped to 22, mine is still at 60, so I guess it's not a performance issue, it's something with asynchronous.

**Comment by AndyEsser** [comment]
Yea could be it's swapping the buffers out of sync with the device screen refreshing so you get flickering and/or screen tearing.

Not sure what to suggest I'm afraid. What hardware are you using?

**Comment by implicit-invocation** [comment]
I'm testing on both iphone simulator and my iphoneX.

**Comment by implicit-invocation** [comment]
My bad, I found out why it flickers, it's gl-texture2d and this line (https://github.com/stackgl/gl-texture2d/blob/master/texture.js#L274)

**Comment by Duckers** [comment]
I am having this same issue.. If there is no solution, then this package isn't very useful :/

**Comment by Duckers** [comment]
Found my culprit: calling `getAttribLocation` per frame. It makes sense that since RN is async then you cannot do any type of `get*` call per frame, as those need to roundtrip with the UI thread. Pretty nasty limitation, but makes sense.

**Comment by tdzl2003** [comment]
`getAttribLocation` `getUniformLocation` will cause same issue. Do these only once after loaded.
