### ISSUE TITLE
Interactive graphics with RN

### ISSUE THREAD

**Issue by dchersey** [react-community/react-native-webgl#59]
Possibly dumb question: (I'm new to GL):

Is there a way to capture/bind to touch events that would trigger Javascript code that would affect the GL graphics?  For example, an i[nteractive voronoi treemap](http://alexbeutel.com/webgl/voronoi.html) rendered in GL?

Many thanks!

**Comment by gre** [comment]
yeah definitely possible,
you can use a react-native PanResponder to capture the touch events & do logic with it.

**Comment by superandrew213** [comment]
There is a good example [here](https://github.com/gre/workshop-gl-react-expo/blob/320ff3bd7131d22e24485ae26eab09fb052f52c5/app/exercices/PaintBrush.js) which @gre just published. Pretty cool 👍

**Comment by gre** [comment]
@superandrew213 thanks for mentioning, yeah I think that's the best example I have today regarding PanResponder vs gl-react , for the voronoi exemple, you can probably combine that `responseToTouchPosition` with a port of the code of http://alexbeutel.com/webgl/voronoi.html

**Comment by dchersey** [comment]
Thanks for the help!  I'm checking out those links; great stuff!
