### ISSUE TITLE
How to achieve randomness for 2D noise function

### ISSUE THREAD

**Issue by zdenham** [react-community/react-native-webgl#60]
Hello! Thanks for the wonderful library!

I am implementing a film grain image effect, and it involves a noise function and the below 2D random function (taken from book of shaders). I was able to implement the effect nicely in webgl, but when using react-native-webgl, the randomness and noise functions both had unexpected and very different outputs than webgl. The following shader:

```
float random(vec2 co){
  return fract(sin(dot(co.xy ,vec2(12.9898,78.233))) * 43758.5453);
}

void main() {
  float rnd = random(v_position);

  gl_FragColor = vec4(vec3(rnd), 1.0);
}
```

Outputed:
<img width="660" alt="webgl" src="https://user-images.githubusercontent.com/16373521/40094416-c37b0134-587b-11e8-90f6-082a2ed45620.png">

In webgl, but in react-native-webgl outputed:
![rnwebgl](https://user-images.githubusercontent.com/16373521/40094451-e7b7ea8a-587b-11e8-9d61-439e37cd2395.jpg)
(which does not appear very random). I am wondering why the output is so inconsistent between the two platforms, if the difference can be remedied, or if it is a hardware problem... Any advice would be greatly appreciated!

**Comment by zdenham** [comment]
Update: this function outputs correctly on simulator (that is the same as webgl), but if built to any real iOS device it outputs something similar to the second image above.

**Comment by gre** [comment]
have you tried to define a `precision` ? like `precision highp float;`

**Comment by zdenham** [comment]
ahhh yes, I had been using mediump. This did the trick! Thank you for your help!
