### ISSUE TITLE
[iOS] `react-native link` seems broken for react-native-webgl

### ISSUE THREAD

**Issue by gre** [react-community/react-native-webgl#7]
> react-native link react-native-webgl seems to be broken for iOS, as it adds libGPUImage.a to the linker instead of libRNWebGL.a.

https://github.com/react-community/react-native-webgl/issues/6#issuecomment-327478948

**Comment by kelset** [comment]
Can confirm, happened to me too.

**Comment by gre** [comment]
I can't find an easy fix for this, so maybe i'll have to switch to recommending manually selecting libRNWebGL.a when configuring

**Comment by themakerman** [comment]
@gre is the linking part solved yet?

**Comment by gre** [comment]
you have to link it manually, it does not work with react-native link, if this is what you asked. I think it's up to RN to fix this.
