### ISSUE TITLE
[RN 0.56] requires 'requiresMainQueueSetup'

### ISSUE THREAD

**Issue by Stan64** [react-community/react-native-webgl#70]
Just installed on a clean RN 0.56 following the instructions for [gl-react-native](https://github.com/gre/gl-react/tree/master/packages/gl-react-native) and then [react-native-webgl](https://github.com/react-community/react-native-webgl). Seems to work fine on iOS except for the error below.

Seems like you need to do something like [this](https://github.com/yamill/react-native-orientation/pull/245/files) to solve it because of elevated permissions.

`Module RNWebGLTextureLoader requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.`

**Comment by kristophM** [comment]
Is this something that will be implemented? Any status on this?
