### ISSUE TITLE
IOS 12 with Xcode 10 Beta?

### ISSUE THREAD

**Issue by dammad** [react-community/react-native-webgl#74]
When I compile with IOS 12/Xcode 10 Beta, I get errors looking for Cocoa/Cocoa.h, etc. It worked before under IOS 11.4. Does anyone have any ideas or pointers?

Dammad
-------
GL-generated-files.hmap -I/Users/alan/Desktop/XXX/myapp/ios/build/Build/Intermediates.noindex/RNWebGL.build/Debug-iphoneos/RNWebGL.build/RNWebGL-own-target-headers.hmap -I/Users/alan/Desktop/XXX/myapp/ios/build/Build/Intermediates.noindex/RNWebGL.build/Debug-iphoneos/RNWebGL.build/RNWebGL-all-target-headers.hmap -iquote /Users/alan/Desktop/XXX/myapp/ios/build/Build/Intermediates.noindex/RNWebGL.build/Debug-iphoneos/RNWebGL.build/RNWebGL-project-headers.hmap -I/Users/alan/Desktop/XXX/myapp/ios/build/Build/Products/Debug-iphoneos/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I../../react-native/React -I../../react-native/React/Base -I../../react-native/React/CxxBridge -I../../react-native/React/CxxModule -I../../react-native/React/CxxUtils -I../../react-native/React/DevSupport -I../../react-native/React/Fabric -I../../react-native/React/Inspector -I../../react-native/React/Modules -I../../react-native/React/Profiler -I../../react-native/React/UIUtils -I../../react-native/React/Views -I../../react-native/React/Base/Surface -I../../react-native/React/Fabric/Mounting -I../../react-native/React/Fabric/Surface -I../../react-native/React/Views/SafeAreaView -I../../react-native/React/Views/ScrollView -I../../react-native/React/Base/Surface/SurfaceHostingView -I../../react-native/React/Fabric/Mounting/ComponentViews -I../../react-native/React/Fabric/Mounting/MountItems -I../../react-native/React/Fabric/Mounting/ComponentViews/ActivityIndicator -I../../react-native/React/Fabric/Mounting/ComponentViews/Root -I../../react-native/React/Fabric/Mounting/ComponentViews/ScrollView -I../../react-native/React/Fabric/Mounting/ComponentViews/Text -I../../react-native/React/Fabric/Mounting/ComponentViews/View -I/Users/alan/Desktop/XXX/myapp/node_modules/react-native/Libraries/Image -I/Users/alan/Desktop/XXX/myapp/node_modules/react-native-webgl/node_modules/react-native/React -I/Users/alan/Desktop/XXX/myapp/node_modules/react-native-webgl/node_modules/react-native/Libraries/Image -Iframework -Iframework/Resources -Iframework/Source -Iframework/Source/Mac -Iframework/Source/iOS -Iframework/Source/iOS/Framework -I/Users/alan/Desktop/XXX/myapp/ios/build/Build/Intermediates.noindex/RNWebGL.build/Debug-iphoneos/RNWebGL.build/DerivedSources/arm64 -I/Users/alan/Desktop/XXX/myapp/ios/build/Build/Intermediates.noindex/RNWebGL.build/Debug-iphoneos/RNWebGL.build/DerivedSources -F/Users/alan/Desktop/XXX/myapp/ios/build/Build/Products/Debug-iphoneos -MMD -MT dependencies -MF /Users/alan/Desktop/XXX/myapp/ios/build/Build/Intermediates.noindex/RNWebGL.build/Debug-iphoneos/RNWebGL.build/Objects-normal/arm64/RNWebGLTextureUIImage.d --serialize-diagnostics /Users/alan/Desktop/XXX/myapp/ios/build/Build/Intermediates.noindex/RNWebGL.build/Debug-iphoneos/RNWebGL.build/Objects-normal/arm64/RNWebGLTextureUIImage.dia -c /Users/alan/Desktop/XXX/myapp/node_modules/react-native-webgl/ios/RNWebGLTextureUIImage.m -o /Users/alan/Desktop/XXX/myapp/ios/build/Build/Intermediates.noindex/RNWebGL.build/Debug-iphoneos/RNWebGL.build/Objects-normal/arm64/RNWebGLTextureUIImage.o
In file included from /Users/alan/Desktop/XXX/myapp/node_modules/react-native-webgl/ios/RNWebGLTextureUIImage.m:2:
In file included from /Users/alan/Desktop/XXX/myapp/node_modules/react-native-webgl/ios/RNWebGLTextureUIImage.h:2:
In file included from /Users/alan/Desktop/XXX/myapp/node_modules/react-native-webgl/ios/RNWebGLTextureWithGPUImage.h:3:
In file included from framework/Source/GPUImage.h:4:
framework/Source/Mac/GPUImageContext.h:16:40: error: unknown type name 'NSOpenGLContext'
@property(readonly, retain, nonatomic) NSOpenGLContext *context;
                                       ^
framework/Source/Mac/GPUImageContext.h:16:1: error: property with 'retain (or strong)' attribute must be of object type
@property(readonly, retain, nonatomic) NSOpenGLContext *context;
^
framework/Source/Mac/GPUImageContext.h:35:24: error: expected a type
- (void)useSharegroup:(CGLShareGroupObj *)sharegroup;
                       ^
In file included from /Users/alan/Desktop/XXX/myapp/node_modules/react-native-webgl/ios/RNWebGLTextureUIImage.m:2:
In file included from /Users/alan/Desktop/XXX/myapp/node_modules/react-native-webgl/ios/RNWebGLTextureUIImage.h:2:
In file included from /Users/alan/Desktop/XXX/myapp/node_modules/react-native-webgl/ios/RNWebGLTextureWithGPUImage.h:3:
In file included from framework/Source/GPUImage.h:6:
framework/Source/Mac/GPUImageView.h:1:9: fatal error: 'Cocoa/Cocoa.h' file not found
#import <Cocoa/Cocoa.h>
        ^~~~~~~~~~~~~~~
4 errors generated.

** BUILD FAILED **

**Comment by cujo30227** [comment]
Hi, I'm experiencing exactly the same errors. Did you find any solution?

**Comment by yohann305** [comment]
**bump**
iOS 12 has deprecated OPENGL ES. So it's going away but it should still work though. Any help is greatly appreciated

**Comment by cujo30227** [comment]
In your case it also seems to be related to GPUImage.. I'll post an Issue there as well

**Comment by cujo30227** [comment]
Hi, I managed to solve it:
Remove the complete contents of framework/Source/Mac/ 
Remove GPUImageMac.xcodeproj

Now all builds correctly!

**Comment by ltgbau** [comment]
> Hi, I managed to solve it:
> Remove the complete contents of framework/Source/Mac/
> Remove GPUImageMac.xcodeproj
> 
> Now all builds correctly!

Thanks, it works!!!!

**Comment by elledienne** [comment]
I didn't try the solution mentioned above, but switching to the [legacy build system](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes/build_system_release_notes_for_xcode_10) worked for me

> If you need it, the legacy build system is still available in Xcode 10. To use the legacy build system, select it in the File > Project/Workspace Settings sheet.

**Comment by b3nab** [comment]
Same error here, I tried @elledienne workaround and it works perfectly. Thanks!

What's changed in the new build system that break the build process?
And the deprecation of OPENGL ES by iOS 12 (as mentioned by @yohann305) will impact the usage of react-native-gl and react-native-webgl ?

**Comment by david-saint** [comment]
Ho

> Hi, I managed to solve it:
> Remove the complete contents of framework/Source/Mac/
> Remove GPUImageMac.xcodeproj
> 
> Now all builds correctly!

Hi, how do I do this? where is framework/Source/Mac?

**Comment by elzii** [comment]
> Hi, how do I do this? where is framework/Source/Mac?

From project root: `rm -rf ./node_modules/react-native-webgl/ios/framework/Source/Mac`
