### ISSUE TITLE
Error compiling Execution failed for task ':react-native-webgl:buildRNWebGLLib

### ISSUE THREAD

**Issue by thisEdgarMarquez** [react-community/react-native-webgl#80]
Hello friends, I have the following error when trying to generate the debug apk of my test app. I hope you can help me

React Native: 58
buildToolsVersion = "28.0.2"
minSdkVersion = 17
compileSdkVersion = 28
targetSdkVersion = 27
supportLibVersion = "28.0.0"

`> Task :react-native-webgl:buildRNWebGLLib FAILED
Android NDK: android-9 is unsupported. Using minimum supported version android-16.    
make: Entering directory `/home/edgarmarquez/imageEditor/node_modules/react-native-webgl/android/src/main/jni'
/home/edgarmarquez/Android/Sdk/ndk-bundle/build/core/add-application.mk:178: *** make: Leaving directory `/home/edgarmarquez/imageEditor/node_modules/react-native-webgl/android/src/main/jni'
Android NDK: APP_STL gnustl_shared is no longer supported. Please switch to either c++_static or c++_shared. See https://developer.android.com/ndk/guides/cpp-support.html for more information.    .  Stop.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-webgl:buildRNWebGLLib'.
> Process 'command '/home/edgarmarquez/Android/Sdk/ndk-bundle/ndk-build'' finished with non-zero exit value 2`

**Comment by AndyEsser** [comment]
If you’re targeting Android 9 (Pie) – you need SDK version 28 (according to: https://source.android.com/setup/start/build-numbers)

**Comment by sunnylqm** [comment]
https://github.com/react-native-community/react-native-webgl/blob/master/android/src/main/jni/Application.mk#L4 or update gradle which can skip unsupported ndk version

**Comment by thisEdgarMarquez** [comment]
Thank you, your answers helped me.
