### ISSUE TITLE
Could not find @ReactModule Annotation in fr.greweb.rnwebgl.RNwebGLTextureloader

### ISSUE THREAD

**Issue by HappyDev96** [react-community/react-native-webgl#81]
Hello
While implementing of gl-react-native, I faced an issue.
The detail of the issue is like following.
Could not find @ReactModule annotation in fr.greweb.rnwebgl.RNWebGLTextureLoader

Who can help me?

**Comment by Blakletter** [comment]
I am having this same problem...It probably has something to do with version incompatibility somewhere. I'll do more digging around

**Comment by JeremyMColegrove** [comment]
It appears as though the call is coming from `react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/CatalystInstanceImpl.java`

Line 438:  
```
private <T extends NativeModule> String getNameFromAnnotation(Class<T> nativeModuleInterface){
    ReactModule annotation = nativeModuleInterface.getAnnotation(ReactModule.class);
    if (annotation == null) {
      throw new IllegalArgumentException("Could not find @ReactModule annotation in " + nativeModuleInterface.getCanonicalName());
    }
    return annotation.name();
  }
```

On the most recent branch 0.59
However in branch 0.57 this call is not being made, meaning it won't error. Try downgrading your version of react-native to 0.57, this worked for me.
**Step 1:**
Run this command to see what version of react you are running: `react-native -version`
**Step 2:**
Downgrade by running: `npm install react-native@x.xx.x`, in this case x.xx.x should be 0.57 in command prompt as Administrator inside your react-native project directory. 
**Step 3:** Rebuild your project.
NOTE: downgrading your react-version may cause other compatibility issues, but the change isn't major. Good luck!
