### ISSUE TITLE
downloadJSCHeaders not working

### ISSUE THREAD

**Issue by mrquanghuy** [react-community/react-native-webgl#88]
# No Template

Hi All. I was follow installizing step
I added gradle-download-task to  android/build.gradle

`dependencies {
        classpath 'de.undercouch:gradle-download-task:3.1.2'
        ...
    }`
but i got an error 
![image](https://user-images.githubusercontent.com/15008133/59185470-bafedc80-8b9a-11e9-966a-0fa710168bb3.png)

my android target version is 9.0
`buildToolsVersion = "28.0.3"
        minSdkVersion = 21
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"`

Any help plz!

**Comment by MriduDixit15** [comment]
did you get solution

**Comment by gre** [comment]
this specific bug was recently fixed
