### ISSUE TITLE
Exception thrown when unloading

### ISSUE THREAD

**Issue by Kernael** [react-community/react-native-webgl#9]
The following code :

```
-(void)unloadWithCtxId:(RNWebGLContextId)ctxId {
  for (NSNumber *key in [_objects keyEnumerator]) {
    RNWebGLTexture *t = _objects[key];
    if (t.ctxId == ctxId) {
      [t unload];
      [_objects removeObjectForKey:key];
    }
  }
}
```
from RNWebGLTextureLoader.m throws this exception : 

`'*** Collection <__NSDictionaryM: 0x1708484c0> was mutated while being enumerated.'`

The exception seems to be thrown only when the code is live reloading.

**Comment by gre** [comment]
this was fixed in a patch today :) https://github.com/react-community/react-native-webgl/commit/6120b7272d7f150ee16dbf1e94645f72a37011fc
