### ISSUE TITLE
Can I use canvas 2D API?

### ISSUE THREAD

**Issue by tomnotcat** [react-community/react-native-webgl#90]
# Feature Request

Can I use canvas 2d api, like web canvas.getContext("2d")

## Why it is needed

For some 2d drawing apps (like drawing board), 2d is simpler.

## Possible implementation

Export 2d api (also based on web standard).

### Code sample

import { CanvasView } from "react-native-webgl";

**Comment by gre** [comment]
not really relevant to this project. it implements webgl context, not 2d context (which could be another lib)
