### ISSUE TITLE
React Native 0.60 support

### ISSUE THREAD

**Issue by Andrei-Vakulski** [react-community/react-native-webgl#92]
# Feature Request

Is there any plans to support latest React Native 0.60 (both platform and [new linking system ](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md))?

Currently, when trying to bootstrap a fresh RN 0.60 app on ios and install react-native-webgl either trying new pod install or old react-native link I'm getting [this error](https://gyazo.com/5c2b5ba60be49681ad1e7eb85a3d7432)

```
Exception '-[RCTCxxBridge jsContextRef]: unrecognized selector sent to instance 0x7f7f4200dd80' was thrown from JS thread

RCTFatal
-[RCTCxxBridge handleError:]
-[RCTCxxBridge _tryAndHandleError:]
__NSThreadPerformPerform
__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
__CFRunLoopDoSources0
__CFRunLoopRun
CFRunLoopRunSpecific
+[RCTCxxBridge runRunLoop]
__NSThread__start__
_pthread_body
_pthread_start
thread_start
```

**Comment by Bartson** [comment]
Any information would be appreciated.

**Comment by gre** [comment]
let's group the discussion on #95
