### ISSUE TITLE
Error on build, react-native 0.60

### ISSUE THREAD

**Issue by vadhack** [react-community/react-native-webgl#93]
Please, can someone help me? 
Error on build, react-native 0.60

## Environment info

React native error output:

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/media/vadhack/store/dev/device/device/node_modules/react-native-webgl/android/build.gradle' line: 90

* What went wrong:
A problem occurred evaluating project ':react-native-webgl'.
> Could not find method leftShift() for arguments [build_7fa2hf3cms3ztdej3yyepuqmp$_run_closure3@53c96882] on task ':react-native-webgl:prepareJSC' of type org.gradle.api.DefaultTask.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-webgl'.
> compileSdkVersion is not specified.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

**Comment by aevzp** [comment]
The same problem
RN 0.59.9

**Comment by AMARAYANK** [comment]
I'm also facing the same problem
RN 0.60.3

**Comment by ghost** [comment]
Looks like the _<<_ operator needs to be replaced with _doLast_ in build.gradle

https://stackoverflow.com/a/55793096

**Comment by vadhack** [comment]
thanks, 

in "/node_modules/react-native-webgl/android/build.gradle

i changed this:

task prepareJSC(dependsOn: downloadJSCHeaders) << {
  copy {
    from {downloadJSCHeaders.dest}
    include 'jni/**/*.so', '*.h', 'Android.mk'
    filesMatching('*.h', { fname -> fname.path = "JavaScriptCore/${fname.path}"})
    into "$thirdPartyNdkDir/jsc";
  }
}


by this:


task prepareJSC(dependsOn: downloadJSCHeaders)  {
  doLast {
    copy {
      from {downloadJSCHeaders.dest}
      include 'jni/**/*.so', '*.h', 'Android.mk'
      filesMatching('*.h', { fname -> fname.path = "JavaScriptCore/${fname.path}"})
      into "$thirdPartyNdkDir/jsc";
    }
  }
}


then worked, but i got other errors related to gradle version:

Task :react-native-webgl:buildRNWebGLLib FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
56 actionable tasks: 56 executed
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':react-native-webgl:buildRNWebGLLib'.
> File '/media/vadhack/store/dev/device/device/node_modules/react-native-webgl/android/src/main/jni' specified for property '$1' is not a file.
> File '/media/vadhack/store/dev/device/device/node_modules/react-native-webgl/cpp' specified for property '$2' is not a file.

**Comment by ghost** [comment]
In _react-native-webgl/android/src/main/jni/Application.mk_, if you change APP_STL to _APP_STL := c++_shared_, and remove the _NDK_TOOLCHAIN_VERSION := 4.9_ line, it seems to compile. Not sure what this breaks though.

**Comment by Bartson** [comment]
I had the same error. I did everything that is contained in this thread but below error occurred. Did you guys linked library? In RN 0.6 I don't really know what should I do when library is not supporting autolinking. 

```1: Task failed with an exception.
-----------
* Where:
Build file '/Users/admin/Desktop/react-native-apps/GLTest/node_modules/react-native-webgl/android/build.gradle' line: 51

* What went wrong:
A problem occurred evaluating project ':react-native-webgl'.
> No such property: sdkHandler for class: com.android.build.gradle.LibraryPlugin``

**Comment by skizzo** [comment]
Any updates on this? I'm on RN `0.59.10` and can't build the project for Android.

**Comment by cesarhilario** [comment]
Same error for me

**Comment by cesarhilario** [comment]
Same error for me
RN 0.60.4

**Comment by gre** [comment]
we can continue the discussion on #95 , many issues was recently addresses but there are now some remaining issues mentionned in #95
