### ISSUE TITLE
'React/RCTViewManager.h' file not found

### ISSUE THREAD

**Issue by pjustino** [react-community/react-native-webgl#94]
# Bug

After installing the npm packages I opened the iOS solution on XCode. When I build the solution it gives me the following error:
   'React/RCTViewManager.h' file not found

![image](https://user-images.githubusercontent.com/11228463/62376647-0e592f80-b539-11e9-9538-ecc21fa98314.png)

## Environment info

React native info output:

```bash
Environment:
  OS: macOS 10.14.4
  Node: 10.15.3
  Yarn: Not Found
  npm: 6.4.1
  Watchman: Not Found
  Xcode: Xcode 10.3 Build version 10G8
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: ^0.49.3 => 0.49.5
```

## Steps To Reproduce

1. clone repo
2. npm i on the root and example folder
3. Open iOS solution with XCode under the exampe folder and build

**Comment by vcellu** [comment]
I am getting the same problem...  Any resolutions?

**Comment by vcellu** [comment]
resolved.  I had to change iOS version to 9.0 in the podspec file

**Comment by lego651** [comment]
Got the same issue. Tried to change iOS version to 9.0 in podspec file. No success...

**Comment by lenichols** [comment]
Still no update on this? Facing the same issue...

**Comment by sensoft2207** [comment]
Any update on this? facing same issue
